#Les représentants de l’état de New York

select ?name 
where{
?p <http://xmlns.com/foaf/spec/name> ?name.
?p <www.example.org/Person/etat> ?x.
?x <http://schema.org/name> "New York".

}


#Le parti représentant de l’état du Minnesota 
select ?party 
where 
{
	?p <http://www.example.org/Party> ?party.
	?p <www.example.org/Party/etat> ?x.
	?x <http://www.example.org/GeoEtat> "Minnesota".
}

#L’image du représentant des Virgin Islands (non car nous ne gérons pas d'image ici)
#Les états représentés par le parti indépendant
select ?etat 
where 
{
	?p <http://www.example.org/GeoEtat> ?etat.
	?p <www.example.org/geoEtat/party> ?x.
	?x <http://www.example.org/Party> "Republican".
}

#La chambre à laquelle appartient les représentants de l’état de American Samoa(cette état n'existe pas, je change par alabama)
select ?chambre 
where
{
	?ch <http://www.example.org/Chambre>?chambre.
	?x  <www.example.org/Chambre/hasParty>?p.
	?p  <www.example.org/Chambre/geoetat>"Alabama".
}

#Les noms des représentants de l’état de l’Alaska(nexiste pas, j'ai remplacer par nevada) triés par ordre alphabétique

select ?name
where
{
	?x <http://xmlns.com/foaf/spec/name> ?name.
	?p <www.example.org/Person/etat> ?x.
	?x <http://schema.org/name> "Nevada".
	ORDER BY ?name
}